### ISSUE TITLE
layer control shows default basemaps only

### ISSUE THREAD

**Issue by noerw** [environmentalinformatics-marburg/mapview#10]
When creating maps with the following commands, the layercontrol shows incorrect basemaps for `map1`. The second variant `map2` shows the correct basemaps though.
I tested this only with rasterbricks, but all datatypes might be affected.

    require(mapview)
    require(raster)
    tif <- brick('fig-1C.tif')

    map1 <- mapview(map.types = c('OpenStreetMap', 'OpenTopoMap', 'Stamen.Toner'))
    map1 <- map1 + tif

    map2 <- mapview(tif, map.types = c('OpenStreetMap', 'OpenTopoMap', 'Stamen.Toner'))

**Comment by tim-salabim** [comment]
Thanks for catching this! It is now fixed in the develop branch. 
Please let us know whether this fixes your problem.

Cheers
Tim

**Comment by tim-salabim** [comment]
This is working now
