### ISSUE TITLE
feature ID (row.names)

### ISSUE THREAD

**Issue by edzer** [environmentalinformatics-marburg/mapview#15]
When querying a feature, it would be nice if in addition to the long/lat and attribute value, the feature ID, obtained by `row.names(obj)`, would appear. This makes it easier to identify administrative districts, or sample IDs.

When clicking in polygons, we don't get the long/lat of the clicked point, but that of the center point of the polygon. I'd suggest to replace long/lat with feature ID (row.name) in case of polygons (and perhaps lines).

**Comment by fdetsch** [comment]
Starting from the most recent 'develop' version (1.0.10), feature IDs (*i.e.*, `rownames`) related with objects of class `SpatialPointsDataFrame`, `SpatialPolygonsDataFrame`, and `SpatialLinesDataFrame` are now being displayed in the pop-up windows. Please note that long/lat coordinates are not explicitly visualized when it comes to the latter, e.g. 
```{r}
mapview(atlStorms2005)
``` 
As for polygons, we should soon decide upon the additional value of centroid coordinates. It does not require too much effort to switch on/off such features in the associated pop-up tables.

**Comment by edzer** [comment]
Great, thanks a lot!

**Comment by tim-salabim** [comment]
Given that we now have `mouseCoordinates` and only show lon/lat coordinates for points I am closing this issue

**Comment by ervanSTRI** [comment]
@tim-salabim : Any chance to specify or change the feature ID in the pop-up table, by either specifying a target column or removing the feature ID line in the table?? Thanks.
