### ISSUE TITLE
Cannot compile github version on MacOSX 10.9.5

### ISSUE THREAD

**Issue by aloboa** [environmentalinformatics-marburg/mapview#16]
After
library(devtools) 
install_github("environmentalinformatics-marburg/mapview", ref = "master") 
I get:
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mapview/libs/mapview.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mapview/libs/mapview.so, 6): no suitable image found.  Did find:
	/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mapview/libs/mapview.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
Error: loading failed
Execution halted

No idea what to do.
Agus

**Comment by tim-salabim** [comment]
Agus,
the problem stems form compiled C++ libraries. There are some problems when the latest compile was done under windows which may well be the case here.
could you please let me know if the problem also occurs when you install the develop branch? 

install_github("environmentalinformatics-marburg/mapview", ref = "develop") 

In case you don't want to stick to the develop version, the version on CRAN is identical to the master branch at giihub, so you could just install mapview via install.packages.

Cheers
Tim

**Comment by aloboa** [comment]
TIm,
Same problem after
** testing if installed package can be loaded
Warning: replacing previous import by ‘leaflet::JS’ when loading ‘mapview’
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mapview/libs/mapview.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mapview/libs/mapview.so, 6): no suitable image found.  Did find:
	/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mapview/libs/mapview.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
Error: loading failed
Execution halted
ERROR: loading failed

The cran version installs fine, but I was told to use the github version for spplot().
Ref. to 
http://r-sig-geo.2731867.n2.nabble.com/resolution-of-openmap-raster-layers-td7589605.html

My problem is that with the cran version mapview_1.0.0, I have problems to select the type of map: I always get the OSM one no matter which one I state. I've tried both
nica <- getData("GADM", country="NIC", level=0)
spplot(mapView(nica["ISO"]),colorkey=FALSE,
       map.type="Thunderforest.Landscape")
and
spplot(mapView(nica["ISO"],map.types="Thunderforest.Landscape"),
     colorkey=FALSE)

despite the fact that just mapView() selects the correct map:
mapView(nica,map.types="Thunderforest.Landscape" )

Note sure about opening an issue for that because it could be solved in the github version
that I cannot install. Perhaps
you could try it?

**Comment by tim-salabim** [comment]
Agus, thanks for checking.
Do you have XCode installed? This sounds like your system is not able to compile the C++ libs and then realising that it cannot read the ones that are shipped as they were, in the case of the "develop" branch, compiled under linux with gcc compiler. 

Regarding your mapview::spplot hopes, I have to currently disappoint you:
Firstly, it is currently merely a wrapper around openmap, so not a remedy for the resolution issue (re: r-sig-geo) and you will only be able to use the map types provided by openmap, not leaflet. Secondly, despite it being under development, it is not top priority as the focus of mapview is interactivity.

**Comment by aloboa** [comment]
I do have XCode installed but the Mac is not my main machine, thus unless you want me to
clarify this aspect of the compilation I would not try further.
I understand your main priority is interactivity, it makes sense. I open an issue for the problem selecting the files with spplot so that at least you have it filed.
What I would really suggest is
including an optional scale bar in mapView(). Many thanks for your work and assistance.
