### ISSUE TITLE
mapview::spplot() does not select type of map

### ISSUE THREAD

**Issue by aloboa** [environmentalinformatics-marburg/mapview#17]
With the cran version mapview_1.0.0, I have problems to select the type of map using mapview::spplot(): I always get the OSM one no matter which one I state. I've tried both
nica <- getData("GADM", country="NIC", level=0)
spplot(mapView(nica["ISO"]),colorkey=FALSE,
map.type="Thunderforest.Landscape")
and
spplot(mapView(nica["ISO"],map.types="Thunderforest.Landscape"),
colorkey=FALSE)

despite the fact that just mapView() selects the correct map:
mapView(nica,map.types="Thunderforest.Landscape" )

**Comment by tim-salabim** [comment]
`mapview::spplot` has been depricated, so I am closing this issue
