### ISSUE TITLE
Legend manipulation in .Rmd leads to deletion of the entire legend

### ISSUE THREAD

**Issue by chamaoskurumi** [environmentalinformatics-marburg/mapview#20]
When integrating a `mapviewOBJECT@map` in a `.Rmd` file, a manipulation of the legend (for example changing the `layer.name`) results in a map that does not include any legend at all.

Try to `knitr` this in a `.Rmd` file:

```{r}
library("mapview")
library("sp")
# load example data
data(meuse)
coordinates(meuse) <- ~x+y
proj4string(meuse) <- CRS("+init=epsg:28992")
# map does not show any legend at all:
mapview(meuse, zcol="copper", layer.name = "Concentration of Copper")@map
```

**Comment by tim-salabim** [comment]
If you set `legend = TRUE`, i.e. 

`mapview(meuse, zcol="copper", layer.name = "Concentration of Copper", legend = TRUE)@map`

you should see a legend. 
However, the specified `layer.name` is ignored. I will open another issue for this though.

Also note that with the current development version there is no need anymore to call the `@map?` slot explicitly when embedding mapview objects in `knitr` calls.

**Comment by tim-salabim** [comment]
This has been resolved. Legend is shown when `legend = TRUE` and layer names are respected.

**Comment by chamaoskurumi** [comment]
perfect, thx

Am 01.06.2016 um 13:14 schrieb tim-salabim:
