### ISSUE TITLE
leaflet dependency

### ISSUE THREAD

**Issue by edzer** [environmentalinformatics-marburg/mapview#28]
Great work. With the CRAN release, I keep seeing `Warning in leafletPolygonsDF(x, map = map, map.types = map.types, zcol = zcol, : Feature labels on mouseover are not supported in the installed version of 'leaflet'. Run devtools::install_github('rstudio/leaflet') to fix this issue.`, also after installing that leaflet version.

See https://edzer.github.io/sp/#interactive-maps-leaflet-mapview

**Comment by tim-salabim** [comment]
This is strange. It works for me. My sessionInfo is

R version 3.3.0 (2016-05-03)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_1.1.0      leaflet_1.0.1.9004

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5         raster_2.5-8        magrittr_1.5        gdalUtils_2.0.1.7  
 [5] munsell_0.4.3       colorspace_1.2-6    viridisLite_0.1.3   lattice_0.20-33    
 [9] foreach_1.4.3       plyr_1.8.4          tools_3.3.0         webshot_0.3        
[13] rgdal_1.1-10        grid_3.3.0          R.oo_1.20.0         png_0.1-7          
[17] latticeExtra_0.6-28 htmltools_0.3.5     iterators_1.0.8     digest_0.6.9       
[21] RColorBrewer_1.1-2  htmlwidgets_0.6     R.utils_2.3.0       codetools_0.2-14   
[25] sp_1.2-3            scales_0.4.0        R.methodsS3_1.7.1   stats4_3.3.0       
[29] satellite_0.3.0

**Comment by tim-salabim** [comment]
I notice also that the scale bar is not shown in the spGallery which should be rendered with the latest github version of leaflet

**Comment by fdetsch** [comment]
I was able to replicate this issue on a Windows machine. The warning message was thrown both when using the [CRAN](https://cran.r-project.org/web/packages/leaflet/index.html) and [GitHub](https://github.com/rstudio/leaflet) version of **leaflet**.

```
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapview_1.1.0      leaflet_1.0.1.9004

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5         raster_2.5-8        magrittr_1.5        gdalUtils_2.0.1.7   devtools_1.11.1    
 [6] munsell_0.4.3       viridisLite_0.1.3   colorspace_1.2-6    lattice_0.20-33     R6_2.1.2           
[11] foreach_1.4.3       plyr_1.8.4          httr_1.1.0          tools_3.3.0         webshot_0.3        
[16] rgdal_1.1-10        grid_3.3.0          R.oo_1.20.0         png_0.1-7           latticeExtra_0.6-28
[21] git2r_0.15.0        withr_1.0.1         htmltools_0.3.5     iterators_1.0.8     yaml_2.1.13        
[26] digest_0.6.9        RColorBrewer_1.1-2  htmlwidgets_0.6     R.utils_2.3.0       codetools_0.2-14   
[31] curl_0.9.7          memoise_1.0.0       sp_1.2-3            scales_0.4.0        R.methodsS3_1.7.1  
[36] stats4_3.3.0        jsonlite_0.9.21     satellite_0.3.0 
```

**Comment by tim-salabim** [comment]
On Linux the solution is to install **leaflet** first and after that install **mapview**. On Windows, I fear we have a problem, as the binaries are built for us and were likely compiled against the CRAN version of **leaflet** so the internal switch in **mapview** will be set to FALSE even if locally we have a newer version of **leaflet**. 

@fdetsch can you try to install from source on Windows after having updated **leaflet** and see if that solve the problem please.

**Comment by edzer** [comment]
This solved it for linux indeed - thanks!

**Comment by fdetsch** [comment]
Works for me, thanks. We need to find a better solution for all Windows users out there, though.

**Comment by tim-salabim** [comment]
I agree, but I fear there's not much we can do... I am not sure whether we can request CRAN to compile Windows binaries against a non-CRAN version of a dependency? The other option is to resubmit to CRAN without the switch until **leaflet** is updated on CRAN. Not my favorite option as the `label` and `scaleBar` are quite essential for a package like **mapview**

Any thoughts?

**Comment by tim-salabim** [comment]
As discussed on the phone, we could release a patch to CRAN where the `warning` is only shown if `verbose = TRUE`. This will at least get rid of the warning every time mapview is called. People will still need to compile locally to 'activate' labels and scaleBar.

**Comment by tim-salabim** [comment]
I have just pushed the patch - only showing the warning when `verbose = TRUE` to both `master` and `develop` branches. 

@fdetsch please test b4 I submit to CRAN. 

In general, I don't see a good solution for enabling these features on windows (and mac) by default for now.

**Comment by fdetsch** [comment]
Using the GitHub version of **leaflet**, this works just fine for both **mapview** branches. However, using the CRAN version of **leaflet**, the following error is thrown.
```
> mapview(breweries91)
Error in leaflet::addCircleMarkers(map = m, lng = coordinates(x)[, 1],  : 
  unused argument (label = label)
```

**Comment by tim-salabim** [comment]
**mapview** needs to be re-compiled after **leaflet** installation as the assessment whether **leaflet** features are available or not is done during compilation.

**Comment by fdetsch** [comment]
True. After re-compiling the package, the error disappears.

**Comment by jcheng5** [comment]
Sorry to necro this but Is there a reason why you are doing the evaluation during compilation time instead of at runtime? By putting the check in a function for example.

**Comment by tim-salabim** [comment]
@jcheng5 the reason is my lack of (functional) programming background. This is a classic case of overthinking / over-complicating an issue. At the time I just couldn't see the easy fix that you're alluding to now. Thanks for this suggestion! I have learned something new and moved this check to a function now:

```
isAvailableInLeaflet <- function() {
  return(
    list(
      lab = "label" %in% names(as.list(args(leaflet::addCircleMarkers))),
      scl = "addScaleBar" %in% ls(getNamespace("leaflet"))
    )
  )
}
```

Though I hope that this is not needed much longer, as I anticipate a CRAN update of **leaflet** soonish (after all the work that has been done lately)? I would like to avoid releasing **mapview** prior to **leaflet** as there are now many other new leaflet features we use in the development version of mapview (e.g. highlighting)

**Comment by jfroeschke** [comment]
I'm trying to update an existing shiny application with leaflet and mapview dependency.  After updating, I can no longer get these packages working correctly.  After reading the suggestions above, I tried the following: 
``install.packages(c('xtable','crosstalk'), dependencies=T)
install.packages("devtools")
devtools::install_github('rstudio/httpuv')
devtools::install_github('rstudio/leaflet')
devtools::install_github('bhaskarvk/leaflet.extras')
install.packages("mapview",  type="source")

library(leaflet)
library(mapview)
## Example 1
leaflet() %>% addTiles() %>% addMouseCoordinates() # with mouse position info

## Example 2
leaflet() %>%
 addTiles('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}') %>% 
addMouseCoordinates()

#R version 3.3.2 (2016-10-31)
#Platform: x86_64-w64-mingw32/x64 (64-bit)
#Running under: Windows 7 x64 (build 7601) Service Pack 1

#locale:
#[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
#[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
#[5] LC_TIME=English_United States.1252    

#attached base packages:
#[1] stats     graphics  grDevices utils     datasets  methods   base     

#other attached packages:
#[1] mapview_1.2.0      devtools_1.12.0    leaflet_1.0.2.9010 crosstalk_1.0.1   

#loaded via a namespace (and not attached):
# [1] Rcpp_0.12.9         RColorBrewer_1.1-2  git2r_0.18.0        plyr_1.8.4         
# [5] R.methodsS3_1.7.1   R.utils_2.5.0       iterators_1.0.8     tools_3.3.2        
 #[9] gdalUtils_2.0.1.7   digest_0.6.11       jsonlite_1.2        viridisLite_0.1.3  
#[13] satellite_0.2.0     memoise_1.0.0       lattice_0.20-34     png_0.1-7          
#[17] foreach_1.4.3       shiny_1.0.0         yaml_2.1.14         curl_2.3           
#[21] rgdal_1.2-5         withr_1.0.2         httr_1.2.1          raster_2.5-8       
#[25] htmlwidgets_0.8     webshot_0.4.0       stats4_3.3.2        grid_3.3.2         
#[29] R6_2.2.0            sp_1.2-4            latticeExtra_0.6-28 magrittr_1.5       
#[33] scales_0.4.1        codetools_0.2-15    htmltools_0.3.5     mime_0.5           
#[37] xtable_1.8-2        colorspace_1.3-2    httpuv_1.3.3        munsell_0.4.3   ''
```

No error is produced (or warning) but the addMouseCoordinates() function does not work. Any guidance on how to get these packages working together again would be greatly appreciated.

**Comment by timelyportfolio** [comment]
@jfroeschke thanks for the report.  See https://github.com/environmentalinformatics-marburg/mapview/pull/53.  @tim-salabim is working to get into master.

**Comment by tim-salabim** [comment]
`devtools::install_github("environmentalinformatics-marburg/mapview", ref = "develop")` should fix this. As a rule of thumb, when you're working the github (https://github.com/rstudio/leaflet) version of **leaflet** you should also work with the development (https://github.com/environmentalinformatics-marburg/mapview/tree/develop) version of **mapview**. **leaflet** uses branch "master" for development (among others), **mapview** uses branch "develop".

Hope that clarifies

**Comment by timelyportfolio** [comment]
Not important, but if you prefer you could also install from a branch with `@`.

```
devtools::install_github("environmentalinformatics-marburg/mapview@develop")
```
