### ISSUE TITLE
na.color="transparent" not works for raster

### ISSUE THREAD

**Issue by earthcli** [environmentalinformatics-marburg/mapview#33]
I found na.color="transparent" not works for raster!

**Comment by tim-salabim** [comment]
please install the development version. It is fixed there:

`
devtools::install_github("environmentalinformatics-marburg/mapview", ref = "develop")
`
Tim

**Comment by earthcli** [comment]
thanks!
it works for raster, while not for spatialpixeldataframe.

**Comment by tim-salabim** [comment]
This should be fixed now also for `SpatialPixelsDataFrame` in the develop branch. Please let me know if it solves your problem.

**Comment by tim-salabim** [comment]
Seemingly solved so closing this
