### ISSUE TITLE
two bugs

### ISSUE THREAD

**Issue by earthcli** [environmentalinformatics-marburg/mapview#34]
1.legend=FALSE not works when the parameter alpha is used for SpatialPixelsDataFrame.
2.LayersControl was missing when saved by mapshot for html while it is normal in RStudio.

**Comment by tim-salabim** [comment]
1. can you provide a reproducible example?

2. This is intended as it is useless for a static map

**Comment by tim-salabim** [comment]
fixed, so closing this
