### ISSUE TITLE
How can I change the initial zoom level for mapview?

### ISSUE THREAD

**Issue by earthcli** [environmentalinformatics-marburg/mapview#37]
1.How can I change the zoom level for mapview?  is there a parameter for setting zoom, or a scale  factor that can change  the default zoom level  with 90% or 80% percent?
2.and how can I change the zoom level change step for mouse action, now the zoom level change from 7 to 8 or 6 when I scroll the mouse, I want that change by 0.5, that is from 7 to 7.5 or 6.5 once.

**Comment by tim-salabim** [comment]
The first you can do with:

```
library(mapview)
library(sp)

m <- mapview(breweries91)
m

cntr_crds <- c(mean(coordinates(breweries91)[, 1]),
               mean(coordinates(breweries91)[, 2]))

m@map %>% setView(cntr_crds[1], cntr_crds[2], zoom = 2)

```

The second is not possible as leaflet.js does only provide zoom changes by 1

**Comment by earthcli** [comment]
That works, many thanks!

**Comment by floswald** [comment]
should add that to somewhere in the docs! this is great
