### ISSUE TITLE
request

### ISSUE THREAD

**Issue by angelini75** [environmentalinformatics-marburg/mapview#42]
Dear @tim-salabim 
Would be nice to add the option to plot a grid of coordinates in the map as well as a (graphical) interactive control of transparency of the layers.

Excellent tool!
Cheers,
Marcos

**Comment by tim-salabim** [comment]
With 'grid of coordinates' do you mean a graticule? If so, that will be available in leaflet soon.
I will look into the interactive transparency options out there

**Comment by angelini75** [comment]
Yes! then it is one of the easiest tools to plot a study area. Perhaps a function mapview::studyarea() whith graticulate, north symbol and scale would be great!

**Comment by tim-salabim** [comment]
North is always up! scaleBar is already there and you can use addExtent() to add a rectangle representing your study area

**Comment by tim-salabim** [comment]
honestly, I don't see the additional value of a studyArea() function. The scope of mapview is to quickly visualise data during the workflow. What you suggests sounds more like a final presentation grade map.

**Comment by angelini75** [comment]
It is fine, mine was just a suggestion. I think the tool is great as it is anyway. However, I think this can be the best tool to plot final maps. There are not too many alternatives to this tool. Maybe ggmap can do something like this (http://rgraphgallery.blogspot.nl/2013/04/rg68-get-google-map-and-plot-data-in-it.html) but mapview can also plot objects from sp, raster and satellite packages at the same time (?). So, I think it could be a useful tool to plot final presentation grade map.

**Comment by mdsumner** [comment]
Sp must be fortify-ied for ggplot2, it is well supported but not well explained, and not reversible (though see spbabel). sf just hit CRAN so it's more important to target using those classes ultimately. At any rate, I am happy to help with this generally

**Comment by tim-salabim** [comment]
I agree, sf integration is of higher priority

**Comment by tim-salabim** [comment]
See this

http://stackoverflow.com/questions/40662029/add-opacity-slider-in-r-leaflet

for an opacity slider option w leaflet map. I think it is on the radar to be implemented in leaflet.extras.
