### ISSUE TITLE
question on leafletPolygons

### ISSUE THREAD

**Issue by mdsumner** [environmentalinformatics-marburg/mapview#46]
In leafletPolygons there is 

https://github.com/environmentalinformatics-marburg/mapview/blob/develop/R/leafletView.R

```R
  x <- spCheckAdjustProjection(x)
  ext <- raster::extent(raster::projectExtent(x, crs = llcrs))
```

but I don't think the projectExtent is required after the adjustment already unprojected if needed?

**Comment by tim-salabim** [comment]
Thanks for catching this. You're right, this is unnecessary as the CRS is already leaflet conform after `spCheckAdjustProjection`.
This is classical 'copy-and-paste' from the first instance which was written for raster objects.  I will clean the code of the entire package when starting to integrate `sf` support.

**Comment by tim-salabim** [comment]
`spCheckAdjustProjection` is not used anymore now that we convert to `sf` internally before doing anything else.
