### ISSUE TITLE
adding legend for slideView()

### ISSUE THREAD

**Issue by danklotz** [environmentalinformatics-marburg/mapview#49]
Dear benefactors at mavpiew, 

Love your package. The slideView function is an amazing tool to compare spatially distbruted rasters, but often it can be usefull to have a legend. 
So I wanted to ask if its possible to add a legend to the slideView function. 
Like [your](http://environmentalinformatics-marburg.github.io/mapview/slideview/slideview.html) example, but with a legend. 

```
library(mapview)
library(raster)

stck1 <- subset(poppendorf, c(1, 1, 1))
stck2 <- subset(poppendorf, c(3, 3, 3))
slideView(stck1, stck2)
```

**Comment by tim-salabim** [comment]
In general, I do like the idea, however, in your example you are referring to RGB images for which a legend does not make much sense in my opinion. 

@swoellauer would you have some time to look into this? 2 separate divs on each side with their own legends. I guess we could simply hijack leaflet legends for this.

**Comment by danklotz** [comment]
well yeah, but one gets the gist.

**Comment by tim-salabim** [comment]
Sorry for the long silence on this. After talking to @swoellauer I think we have a plan of action now that should enable legends in both slideView and plainView.

**Comment by tim-salabim** [comment]
@swoellauer I have just pushed an update that passes the filename of the legend png via the htmlwidget in plainview - RasterLayer method. Can you please check whether that is sufficient for adding a legend this way.

```r
library(mapview)
plainview(poppendorf[[5]], legend = TRUE)
```

This should produce a valid `x.leg_fl` on the JS side which points to the legend png.

This is a rough implementation so far as the dimensions of the png are fixed (500 x 200 pixels height and width). I am yet to come up with a clever way to estimate the ratio properly (this is mainly depending on the values of the ticks - in the example above these are largish numbers so should be fine in most occasions, but still...). Also, this means that there is some white space (actually transparent space) around the legend, meaning we will need to find a way to crop/clip the png. This could easily be done on the R side using [the magick package](https://github.com/ropensci/magick), yet I am a bit reluctant towards adding another dependency to mapview if not really needed. So, if there is a way to crop the image in JS (without adding another library dependency) then this would be great. If there isn't, then I guess importing the relevant function from **magick** is something we need to consider. 

@danklotz this is currently only a test implemented in `plainview` for the easiest case of rendering a `RatserLayer` but if this works, adding the same to `slideview` should be straight forward.

**Comment by tim-salabim** [comment]
@danklotz We have a first working legend for `plainview` can you please let us know if this is what you are after? `plainview(poppendorf[[5]])`

@swoellauer can we make this flexible, so that `plainview(poppendorf[[5]], legend = FALSE)` doesn't throw an error?

**Comment by danklotz** [comment]
Sorry for the alte replay. 

- The first commit (~8 days ago) did not work, but the current dev-version does! As u said it looks a bit rough around the edges but would be exactly what I imagined (if implemented in `slideview`). Thank you very much 💃 💃 💃

**Comment by tim-salabim** [comment]
@danklotz could you be more specific regarding 'a bit rough around the edges'? So we can try to smooth things... ;-)

**Comment by danklotz** [comment]
Oh... Well this might be picky, but the rendering/transparency of the font seems off. One can see slight white pixels around it.

**Comment by tim-salabim** [comment]
@danklotz what OS are you using? I don't see any rendering issues on Linux...

@swoellauer I have just updated the R side of cube and plainview to include laegends. Can you adjust JS side to enable legend rendering?

**Comment by danklotz** [comment]
used windows. Will check it on mac os to then

**Comment by tim-salabim** [comment]
@danklotz `slideview` and `cubeview` now also have legends (for numeric data). Testing welcome. Regarding the rough look, I can replicate that on windows and will look into that. Linux seems to render fine. Did get a chance to try on mac?

**Comment by tim-salabim** [comment]
Here's what it looks like on linux

![screenshot from 2017-03-06 07 53 19](https://cloud.githubusercontent.com/assets/2826432/23738925/10a2ba72-049c-11e7-9179-977692e61b7d.png)

**Comment by danklotz** [comment]
Mac rendering looks fine to! Attached a screenshot of the `plainview` example from above. 
![mac](https://cloud.githubusercontent.com/assets/7629007/23751161/5e303f38-04d0-11e7-8922-80658253aa3c.png)

**Comment by fdetsch** [comment]
`plainview` works like a charm on Windows as well:
![plainview](http://i.imgur.com/dIb4VSj.png)

**Comment by tim-salabim** [comment]
Thanks @fdetsch ! The issue of bad font rendering of the legend under windows seemed to have been antialiasing. I have now set `antialiasing = "none"` which seems to resolve this. See a73462c4deb202bca89064983d3ac69e94b916f9
