### ISSUE TITLE
Error: pandoc document conversion failed with error 251 

### ISSUE THREAD

**Issue by cemppa** [environmentalinformatics-marburg/mapview#52]
I'm trying to export my mapview in R using built-in mapview-function called mapshot. I get this error message:

**pandoc.exe: Out of memory

Error: pandoc document conversion failed with error 251

In addition: Warning message: running command 'C:/PROGRA~2/Pandoc/pandoc +RTS -K512m -RTS ...**

How do I increase the Pandoc memory size permanently or even temporary in R **without** using a Rmarkdown-file? Is there a handle for this? The function in question is called mapshot, for example mapshot(m, url=paste0(getwd(), "/heatmap.html")).

**Comment by tim-salabim** [comment]
Can you provide an example that reproduces the error?

**Comment by cemppa** [comment]
For example: 	
mapview(testmap, burst=T, zcol=c("x", "y", "z"), alpha.regions = "0.4", legend=T, layer.name=c("x","y","z")) After this I can export this mapview from Rstudio using the built-in export-tool, i.e. create a standalone html file OR I can use function mapshot(m, url=paste0(getwd(), "/heatmap.html")). m being the mapview I created. Either way, I get the same error message.

**Comment by tim-salabim** [comment]
What I meant is that it would be helpful if you could provide a reproducible example that I can work with and debug. I don't know what `testmap` is, so I cannot reproduce your error. Also, what is your `sessionInfo()`?

**Comment by cemppa** [comment]
A reproducible  example would be quite hard as I use private data.
This is the bit where it goes wrong, I think: fp = readOGR("C:/Analyysi","postinumerot") %>% spTransform(CRS("+proj=longlat +datum=WGS84"))
testimap = merge(fp, data, by.x="Name", by.y="postal_code")
testimap<-testimap[,-(2:12)]
mapview(testimap, zcol="Orders", alpha.regions = "0.4", legend=T, layer.name="Sum of Orders")

The data consists of 21 colums and 4311 rows. I'm using polygon data, e.g I have all the postal code areas drawn on the map, and each postal code area has 21 variables. 

Also, Rstudio keeps crashing most of the time when I call this mapview it runs fine on core R.



Sessioninfo is as follows: > sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Finnish_Finland.1252  LC_CTYPE=Finnish_Finland.1252    LC_MONETARY=Finnish_Finland.1252 LC_NUMERIC=C                     LC_TIME=Finnish_Finland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] memisc_0.99.8       MASS_7.3-45         raster_2.5-8        mapview_1.2.0       leaflet_1.0.2.9010  formattable_0.2.0.1 data.table_1.10.0   Hmisc_4.0-1         Formula_1.2-1       survival_2.40-1     lattice_0.20-34     ggmap_2.6.1        
[13] ggplot2_2.2.0       rgeos_0.3-21        magrittr_1.5        rgdal_1.2-5         sp_1.2-3

**Comment by tim-salabim** [comment]
Can you do me a favour and try the following:

```
library(mapview)
library(raster)

usa <- getData("GADM", country = "USA", level = 2)

m <- mapview(usa)

mapshot(m, url=paste0(getwd(), "/heatmap.html"))
```
This data has 15 columns and some 3k+ rows, so close to your data size. On my machine this does not reproduce your error (at least not after running for about 15 min - when I killed it), yet I am on a linux machine with 8GB RAM and 32GB SWAP which both get filled pretty heavily. Also, if this does work on your machine, what is the size of the generated `html` file?

**Comment by cemppa** [comment]
No luck, although it created a html-file sized 93mb.
`> library(mapview)
> library(raster)
> 
> usa <- getData("GADM", country = "USA", level = 2)
> 
> m <- mapview(usa)
Warning message:
In spCheckObject(x) :
  Columns CCN_2 in attribute table contain only NA values and are dropped.
> 
> mapshot(m, url=paste0(getwd(), "/testmap.html"))

pandoc.exe: Out of memory
Error: pandoc document conversion failed with error 251
In addition: Warning message:
running command 'C:/PROGRA~2/Pandoc/pandoc +RTS -K512m -RTS C:\Users\nikkila\Documents\testmap.html --from markdown --output C:\Users\nikkila\Documents\testmap.html --self-contained --template C:\Users\nikkila\AppData\Local\Temp\Rtmp4uIOmn\file2db86da543cf.html' had status 251 `

**Comment by tim-salabim** [comment]
I'd call that luck, as I now have an example that reproduces your error (kind of). I will investigate further...

**Comment by tim-salabim** [comment]
Ok, can you please try with the latest development version of mapview from github setting `selfcontained = FALSE` in `mapshot`:

```
devtools::install_github("environmentalinformatics-marburg/mapview", ref = "develop")
library(mapview)
library(raster)

usa <- getData("GADM", country = "USA", level = 2)

m <- mapview(usa)

mapshot(m, url=paste0(getwd(), "/heatmap.html", selfcontained = FALSE))
```
Let me know if the error still persists.

**Comment by cemppa** [comment]
I ran Rstudio as administrator just to be safe and I get this error: `*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'V8'
ERROR: lazy loading failed for package 'mapview'
* removing 'C:/Users/nikkila/Documents/R/win-library/3.3/mapview'
* restoring previous 'C:/Users/nikkila/Documents/R/win-library/3.3/mapview'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Users\nikkila\Documents\R\win-library\3.3\00LOCK-environmentalinformatics-marburg-mapview-53e085c\mapview\libs\x64\mapview.dll to C:\Users\nikkila\Documents\R\win-library\3.3\mapview\libs\x64\mapview.dll: Permission denied
Error: Command failed (1)`

**Comment by cemppa** [comment]
Yes, it works! I tried it with multiple layers also. Thanks and a happy new year!

**Comment by tim-salabim** [comment]
Sweet! Happy New Year to you too!
