### ISSUE TITLE
installing mapview

### ISSUE THREAD

**Issue by DebsApp** [environmentalinformatics-marburg/mapview#55]
Hi I am trying to install mapview -
>**install.packages("mapview")**
Installing package into ‘/Volumes/Users/debasish/Library/R/3.3/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/mapview_1.2.0.tgz'
Content type 'application/x-gzip' length 2821011 bytes (2.7 MB)
==================================================
downloaded 2.7 MB
The downloaded binary packages are in
	/var/folders/5_/f8l_q2590_z_30dr30f8n60h00017z/T//RtmpvtOO6i/downloaded_packages

**> library(mapview)**
Error in get(method, envir = home) : 
  lazy-load database '/Volumes/Users/debasish/Library/R/3.3/library/rgdal/R/rgdal.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
Error: package or namespace load failed for ‘mapview’

I was trying using github -

**> library(devtools)
> install_github("environmentalinformatics-marburg/mapview")**
Downloading GitHub repo environmentalinformatics-marburg/mapview@master
from URL https://api.github.com/repos/environmentalinformatics-marburg/mapview/zipball/master
Installing mapview
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/5_/f8l_q2590_z_30dr30f8n60h00017z/T/RtmpvtOO6i/devtools44a469623d6c/environmentalinformatics-marburg-mapview-f6a67f6'  \
  --library='/Volumes/Users/debasish/Library/R/3.3/library' --install-tests 

* installing *source* package ‘mapview’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Volumes/Users/debasish/Library/R/3.3/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Volumes/Users/debasish/Library/R/3.3/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c brewCppFun.cpp -o brewCppFun.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Volumes/Users/debasish/Library/R/3.3/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c mapviewCppFun.cpp -o mapviewCppFun.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o mapview.so RcppExports.o brewCppFun.o mapviewCppFun.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Volumes/Users/debasish/Library/R/3.3/library/mapview/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Warning in runHook(".onLoad", env, package.lib, package) :
  internal error -3 in R_decompress1
Error in runHook(".onLoad", env, package.lib, package) : 
  lazy-load database '/Volumes/Users/debasish/Library/R/3.3/library/rgdal/R/rgdal.rdb' is corrupt
ERROR: lazy loading failed for package ‘mapview’
* removing ‘/Volumes/Users/debasish/Library/R/3.3/library/mapview’
* restoring previous ‘/Volumes/Users/debasish/Library/R/3.3/library/mapview’
Error: Command failed (1)

How to fix this problem.

with regards
-Deb

**Comment by tim-salabim** [comment]
This is not a mapview issue. 
According to this http://stackoverflow.com/questions/34593159/failing-to-load-the-new-ggplot2-in-r restarting R should do the trick.

**Comment by DebsApp** [comment]
I have tried by restarting R but I am keep getting the error

**Comment by tim-salabim** [comment]
I guess your best bet is to ask on R-sig-geo or post it on Stackoverflow. The problem seems to arise with rgdal not mapview so there is little we can do here

**Comment by tim-salabim** [comment]
I just had a similar error message. Make sure to install in a fresh session (i.e. not have mapview or any of the dependencies loaded at time of installation).

**Comment by DebsApp** [comment]
Hi
It is working now. Although I removed all the packages from my library and
then install mapview.

Thank you so much for your help.
-Deb
