### ISSUE TITLE
Removing zoom to option

### ISSUE THREAD

**Issue by WandaB** [environmentalinformatics-marburg/mapview#56]
Hi,

How do you remove the 'zoom to' option from the map? See attached picture, under the legend. 

Many thanks,
Wanda 

![2017-01-31 13_00_42-viewer zoom](https://cloud.githubusercontent.com/assets/10597734/22465946/fe183ae2-e7b5-11e6-8d80-99e06b969673.png)

**Comment by timelyportfolio** [comment]
@WandaB, please include reproducible code next time.  I include some code below to accomplish removal of the zoom-to home buttons.

```
library(mapview)

# get the leaflet instance
mp <- mapview(breweries91)@map

# show where the zoom to calls exist
mp$x$calls
# more specifically
Filter(
  function(cl) {
    cl$method == "addHomeButton"
  },
  mp$x$calls
)

# write a function to remove all zoom to calls
#   use the Filter above but change == to !=
remove_zoomto <- function(leafmap) {
  if(inherits(leafmap, "mapview")) {
    leafmap <- leafmap@map
  }
  
  leafmap$x$calls <- Filter(
    function(cl) {
      cl$method != "addHomeButton"
    },
    mp$x$calls
  )
  
  leafmap
}

# try it out
remove_zoomto(mp)

# try with a mapview
remove_zoomto(
  mapview(breweries91)
)
```

**Comment by WandaB** [comment]
Many thanks for the reply. 

I have used a very simple code: 
Survey <- SpatialPointsDataFrame(data[,c("Longitude", "Latitude")], data[,1:4])
proj4string(Survey) <- CRS("+init=epsg:4326")
mapview(Survey, zcol = "Year", burst = TRUE, legend = TRUE)

And according to this the zoom to function appears automatically on the map. 

Your code didn't work for me.

**Comment by timelyportfolio** [comment]
@WandaB, please include the error next time.  I spotted the error and fixed in the above reply.  Also, I have added a reproducible example that seems similar to your objective.

```
# example from ?mapview
library(mapview)
library(sp)

data("meuse")
coordinates(meuse) <- ~x+y
proj4string(meuse) <- CRS("+init=epsg:28992")

mapview(meuse, zcol = "soil", burst = TRUE) # three layers

# write a function to remove all zoom to calls
#   use the Filter above but change == to !=
remove_zoomto <- function(leafmap) {
  if(inherits(leafmap, "mapview")) {
    leafmap <- leafmap@map
  }
  
  leafmap$x$calls <- Filter(
    function(cl) {
      cl$method != "addHomeButton"
    },
    leafmap$x$calls
  )
  
  leafmap
}

remove_zoomto(
  mapview(meuse, zcol = "soil", burst = TRUE)
)
```

**Comment by WandaB** [comment]
This worked, thank you.

**Comment by tim-salabim** [comment]
This can also easily be avoided by setting `homebutton = FALSE`
```r
library(mapview)
library(sp)

data("meuse")
coordinates(meuse) <- ~x+y
proj4string(meuse) <- CRS("+init=epsg:28992")

mapview(meuse, zcol = "soil", burst = TRUE, homebutton = FALSE) 
```

**Comment by michaeldgarber** [comment]
In case someone lands on this old page via a web search, note that mapview now has a function called removeMapJunk: https://r-spatial.github.io/mapview/reference/removeMapJunk.html

For example:
```
library(mapview)
mv_breweries_with_junk = mapview(breweries)
mv_breweries_without_junk = removeMapJunk(mv_breweries_with_junk, junk = c("zoomControl", "layersControl"))
mv_breweries_without_junk
```
