### ISSUE TITLE
popup dimensions: alternative to altering brewPopupTable/popup.brew?

### ISSUE THREAD

**Issue by daauerbach** [environmentalinformatics-marburg/mapview#64]
The default popupTable is great, but in some cases I'd like to adjust the size of the popup div (make it wider when I have string attributes).

Before I screw things up by altering `system.file("templates/popup.brew", package = "mapview")` is there a preferred/easy route to doing this? Please forgive if I'm missing any obvious options somewhere.

(FWIW, I'm not seeing a change in the output when I manually overwrite the `max-width: 100%` to, for example, `max-width: 500px` in the html strings of a mapview object, i.e., the `@map$x$calls[[i]]$args[[9]]`. Played around with a few other things without much luck...)

**Comment by tim-salabim** [comment]
In the above mentioned commit I've set `max-width: 2000px;` This seems to work. 
![screenshot from 2017-03-18 15 21 47](https://cloud.githubusercontent.com/assets/2826432/24073002/5716e55e-0bf0-11e7-9124-7807bf4e3413.png)
Please let me know if this resolves your issue.
