### ISSUE TITLE
dollar operator for class mapview

### ISSUE THREAD

**Issue by brry** [environmentalinformatics-marburg/mapview#68]
I mapped an sfc_MULTIPOLYGON ESRI shapefile but cannot save it to html because: `$ operator not defined for this S4 class` (which is "mapview").

Problem outline:

```R
SHP <- sf::st_read("shapefile.shp")
MAP <- mapview::mapview(SHP)
htmlwidgets::saveWidget(MAP, "map.html")
```
```
Error in x$width : $ operator not defined for this S4 class
```
More details:

```R
str(SHP)
Classes ‘sf’ and 'data.frame':	580 obs. of  4 variables:
 [...]
 $ Anbaujahre   : chr  "2007" "2009" "2010" "2010" ...
 $ geometry     :sfc_MULTIPOLYGON of length 580; first list element: List of 1
  ..$ :List of 1
  .. ..$ : num [1:53, 1:2] 3353047 3353063 3353062 3353053 3353018 ...
  ..- attr(*, "class")= chr  "XY" "MULTIPOLYGON" "sfg"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA
  ..- attr(*, "names")= chr  "Anzahl_J" "AREA_ha" "Anbau"
 - attr(*, "sf_column")= chr "geometry"


htmlwidgets::saveWidget(map, "Maisanbau.html")
Error in x$width : $ operator not defined for this S4 class


traceback()
3: resolveSizing(x, x$sizingPolicy, standalone = standalone, knitrOptions = knitrOptions)
2: toHTML(widget, standalone = TRUE, knitrOptions = knitrOptions)
1: htmlwidgets::saveWidget(map, "Maisanbau.html")
```

Is mapview missing something here? Or am I?

Seems related to https://github.com/environmentalinformatics-marburg/mapview/issues/43 but I don't see how to solve this one...

**Comment by tim-salabim** [comment]
If you want to access the map widget in **napview** you need to specify the `@map` slot, thus `MAP@map`. This should take care of the `saveWidget` call.

**Comment by brry** [comment]
Yes this works, thanks so much!
For people new to mapview, it might be helpful to document this in [mapshot.R](https://github.com/environmentalinformatics-marburg/mapview/blob/develop/R/mapshot.R).

For future readers: Self-contained htmls are still limited to maps that are not too large, see https://github.com/environmentalinformatics-marburg/mapview/issues/69
