### ISSUE TITLE
Being able to use saveWidget for mapview object

### ISSUE THREAD

**Issue by zwep** [environmentalinformatics-marburg/mapview#70]
From some stackoverflow I saw that leaflet objects are able to be saved by the function call saveWidget... however, mapview objects are not.
Since the mapviewer package is a wrapper around leaflet, why isnt this possible? 

(The reason is, I want to save the output of the mapview() function (which is an .html page))

**Comment by tim-salabim** [comment]
See https://github.com/environmentalinformatics-marburg/mapview/issues/68
or use function `mapview::mapshot` which handles mapview objects
