### ISSUE TITLE
mapview in R shiny

### ISSUE THREAD

**Issue by paimazumder** [environmentalinformatics-marburg/mapview#9]
Hi 
I create an interactive map using mapView 
example 
mapView(hspdf, "CDP", fill = TRUE, color = cr, alpha.regions = 0.8) 
where hspdf is hexagonal polygons , CDP are corresponding values of each polygon. 

Now I put that in R shiny but I am getting error as R shiny does not have function related mapView.
However it has function for leaflet which doesn't nor work for mapview.
Is there any way to put mapview within R shiny or How to change mapView (mentioned above) to leaflet?

with regards
-Debasish

0

**Comment by tim-salabim** [comment]
Hi there Debasish,

have a look here

https://metvurst.wordpress.com/2015/12/16/mapview-1-0-0-now-on-cran/comment-page-1/#comment-215

and let us know if this solves your problem.

Cheers
Tim

**Comment by paimazumder** [comment]
Thank you so much Tim. I am looking for bViewOutput and renderbView. Its still not working as they are not in Shiny. Do I need to link xvecView.R to my code somehow?
-Debasish

**Comment by paimazumder** [comment]
Thank you so much Tim. I tried with bView and fpView. Its runs but I get following error message :

Warning: Error in >=: comparison (5) is possible only for atomic and list types
Stack trace (innermost first):
    72: eval
    71: eval
    70: subset.data.frame
    69: subset
    68: func [/Volumes/Users/debasish/Documents/ECEP/App_development/Test/server.R#43]
    67: output$map
     1: shiny::runApp

Any Idea? 
-Debasish

**Comment by tim-salabim** [comment]
How many and what type of features are you wanting to display? 

mapview has a cutoff limit of 20000 for points and 30000 for lines and polygons. Everything beyond that threshold will be rendered using the special functions fpView (for points) and bView (for lines and polygons). Everything below that threshold is rendered using standard leaflet functionality so renderLeaflet should work in this occasion.

Here's some code that works for me (for 50000+ points):

server.R:

    library(shiny)
    library(mapview)
    library(ggplot2)
    library(sp)

    shinyServer(function(input, output, session) {

      repInput <- reactive({
        ### blow diaminds up a bit
        reps <- round(input$numpts / nrow(diamonds), 0)

        big <- as.data.frame(diamonds[rep(seq_len(nrow(diamonds)), reps),],
                             stringsAsFactors = FALSE)
        big$cut <- as.character(big$cut)
        big$color <- as.character(big$color)
        big$clarity <- as.character(big$clarity)

        ### provide some random positions
        big$x <- rnorm(nrow(big), 0, 5)
        big$y <- rnorm(nrow(big), 0, 5)
        coordinates(big) <- ~x+y
        proj4string(big) <- CRS("+init=epsg:4326")
        big
      })

      output$mapplot <- mapview:::renderfpView({
          mapview:::fpView(repInput(),
                           zcol = NULL,
                           color = "blue",
                           na.color = "transparent",
                           values = NULL,
                           map.types = mapviewGetOption("basemaps"),
                           alpha = 1,
                           weight = 4,
                           verbose = FALSE,
                           layer.name = "big",
                           popup = NULL)
        })
    })

ui.R:

    library(shiny)
    library(shinydashboard)
    library(mapview)

    header <- dashboardHeader(title="Points")

    sidebar <- dashboardSidebar(
      fluidPage(
        # Application title
        titlePanel("visualize many points"),
        fluidRow(
              numericInput("numpts", "approximate number of points (50000 - 1000000):",
                       value = 100000, min = 50000, max = 1000000, step = 10000),
          submitButton("Update View", icon("refresh")))
      )
    )

    body <- dashboardBody(
      # Define UI for application
      fluidPage(
        mainPanel(
          mapview:::fpViewOutput("mapplot")
        ))
    )

    ui <- dashboardPage(header, sidebar, body, skin="black")


Hope that helps,

Tim

**Comment by paimazumder** [comment]
Thanks for your suggestion. Shiny script is running. However I am still having couple problems.
1.color hexagonal polygon
here is my mapview 

 require(colorRamps)
cr = colorRampPalette(brewer.pal(9,"YlOrRd"))(100)
mapview:::bView(hspdf,"CDP",
                    zcol = NULL,
                    na.color = "transparent",
                    values = NULL,
                    color = cr,
                    map.types = mapviewGetOption("basemaps"),
                    layer.name = "big",
                    alpha.regions = 0.5) 

However it plots all the polygon in same color but I am trying plot in different colors (cr).

[2] When trying to plot for different time, it plots the earlier plot for second time instead of new plot on top of the earlier plot. map type box also appears on the plot each time rerun scripts.

But when I plot using mapview (without RShiny), it works perfectly fine.

with regards
-Deb

**Comment by tim-salabim** [comment]
Deb,
regarding 1. we are still in the process of integrating color matching for large data sets. At the moment it is not possible to map color to a parameter, but I hope we will resolve this soon.

2. I can only test this if you could somehow make the data and shiny code accessible. 

Tim

**Comment by paimazumder** [comment]
Hi Tim,

Thanks for your response. Could you please provide me your email address.

with regards
-Deb

**Comment by tim-salabim** [comment]
tim.appelhans at gmail com

**Comment by paimazumder** [comment]
Hi Tim,

I have sent you my r and Shiny scripts. Thanks for all your help in this regard.

-Deb
